<?php

namespace Database\Seeders;

use App\Models\Member;
use Illuminate\Database\Seeder;

class MembersSeeder extends Seeder
{
    public function run(): void
    {
        $members = [
            'ABRAHAO LIMA',
            'Aldryn Castro',
            'Kaline Castro',
            'Allana Silva Baima',
            'Ana Carolina Sá Mascarenhas',
            'Ana Claudia de Sá Mascarenhas',
            'Ana Tirza de Padua Sousa',
            'Anderson Santos',
            'Sandra Santos',
            'Andresa Abreu',
            'Beatriz Rodrigues',
            'Benylda Araujo Pinheiro',
            'Bernadeth Cunha Montachiari',
            'Bianca Leticia Silva Ramos',
            'Caique Miller dos Santos Silva',
            'Carlos Augusto Vasconcelos',
            'Caue Vinicius dos Santos Silva',
            'Chiara Saldanha',
            'Clarice Costa Pinheiro',
            'Cleide Soares Barros',
            'Cleilson Silva',
            'Cleunice Teixeira Alves Silva',
            'Conceição de Maria Ramos de Sousa - Concita',
            'Cristiane Pinheiro Andrade Leite',
            'Daniel Beserra',
            'Daniel Chagas Sousa',
            'Danielle Potiguara de Oliveira Costa',
            'DORA SANTOS CAMELO',
            'EDILEUZA SALES',
            'Elaine Cruz Freire',
            'Elizete Alves de Oliveira',
            'Erico Murilo Monteiro Cutrim',
            'Fabiane Silva',
            'Fabrizio Carvalho Saldanha',
            'Felipe Lima Castro',
            'Fernando Campelo',
            'Livia Campelo',
            'FERNANDO J FEL',
            'Fernando Ramon Sousa Cutrim',
            'Francisca Vasconcelos',
            'Gabriel de Jesus',
            'Gabriel Vasconcelos',
            'Kalma Vasconcelos',
            'Gabriel Santos',
            'Gilvan Ribeiro Costa',
            'Hilton Gomes',
            'Heber de Pádua Sousa',
            'Inaldo Pereira Lima',
            'Iracama Araujo Pinheiro Souza',
            'Isabel Santana Santos Cutrim',
            'Janaina de Jesus Privado',
            'Jaqueline Santos Costa Leite',
            'Jeferson Lustosa',
            'JENNIFER NAYARA HUMBELINO DE CARVALHO',
            'Jessica C. Lemos',
            'Joao Alberto de Andrade',
            'Joao Santos Costa',
            'Joao Viana dos Passos Neto',
            'Joao Vitor Santos',
            'Jonathas Vieira da Silva',
            'Jose Carlos',
            'Noabi',
            'Jose Luiz de Araujo',
            'Jose Roberto Pinheiro',
            'Juliana Ramos',
            'Julyana da Silva',
            'Junia Maria Sanches S. dos Passos',
            'Juracy Herminia R. da Silva',
            'Karina Azevedo',
            'Kauã Nogueira',
            'Katia Regina Costa Abreu',
            'Lais Sanches',
            'Neilson Barbosa',
            'Laura Laryssa',
            'LAYNA F SOUZA',
            'Leo Jonathas da Sá Veloso',
            'LETICIA ALVES C SILVA',
            'Lia Raquel Sá',
            'Lia Raquel da Hora',
            'Lidia Agnes Oliveira Lustosa',
            'Lidia Gomes de Araújo Vieira',
            'Lidia Soeiro Cutrim',
            'Lucas Costa dos Santos',
            'Lusenir Eusebi Duarte',
            'Luciany Cristina de Sousa Ferreira Miranda',
            'MARCOS ROBERTO',
            'Marcus Vinicius',
            'Maria Cristina Lustosa',
            'Maria das Neves N. Costa',
            'Maria de Lourdes',
            'Maria do Socorro de Carvalho Araújo',
            'Maria Goreth B. da Silva',
            'Maria Jesus-Co',
            'Maria Jose Carvalho Saldanha',
            'Maria Luiza de Azevedo Pinheiro',
            'Maria Pereira Oliveira',
            'Maria Rosa Barros',
            'Maria Socorro Araujo',
            'Maria Socorro Mendes',
            'Matheus Cisneiros',
            'Meire Borges Saldanha',
            'Naimar de Pádua Pereira',
            'Nair Pereira de Pádua Sousa',
            'Nathalia Barros',
            'Nelma Lima Castro',
            'Ney Cutrim',
            'Noemi Barbosa da Silva',
            'Nyelsen Vieira',
            'Katia Vieira',
            'Ofertas IDENTIFICADAS',
            'ORSON A FERES',
            'Paulo Potiguara',
            'Areli Potiguara',
            'Paulo Farias P',
            'Pedro Lucas dos Passos Campelo',
            'Pedro Samuel Almeida Silva',
            'Quitéria Andrade',
            'Rafael B. Goulart',
            'Rafaela Soares',
            'Raissa Marinho Lima dos Passos',
            'RITA DE CASSIA',
            'Robson Rodrigues',
            'Rommy Cisneiro',
            'Salomão Mateus Brito',
            'Samuel Chagas',
            'Fatima Chagas',
            'Samuel Rocha da Silva',
            'Samuel Saldanha',
            'Sandra Maria Santos',
            'Siliomar',
            'Taiandro',
            'TIAGO FELIX DOS PASSOS CAMPELO',
            'Tiago Pontes P.',
            'Zuleide Oliveira',
            'WILLIAN PEREIRA',
            'Vinicius Oliveira Lustosa',
        ];

        foreach ($members as $name) {
            Member::firstOrCreate([
                'name' => $name,
            ], [
                'status' => 'active',
                'is_member' => true,
            ]);
        }
    }
}
